### PR TITLE
WIP: Add expo PR preview apps. #94.

### PR DESCRIPTION
**Pull request by mehdisadeghi**

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
@carocad have a look at travis logs. For any reason exp login fails.

**Comment by carocad** [comment]
@mehdisadeghi it seems this was a mere typo problem.

I changed your expo credentials by mine and it correctly logged in.

We have another problem now though. The build fails because we havent exposed the init.json to the app itself. I guess we would have to use something like env vars.

**Comment by carocad** [comment]
on another topic. Usually both exp and react native *chock* on the output from the clojurescript compiler.

It seems that those packagers were made with the assumption that they will have lots of little files which can be processed separatedly. Clojurescript on the other hand, creates a single minified file; which those packagers dont like.

That might become a problem for us as the app grows bigger

**Comment by carocad** [comment]
@mehdisadeghi I think the init.json problem can be solved with env vars. But I wont be able to work on this now. Maybe tonight? not sure but it can be solve easily ;)

**Comment by mehdisadeghi** [comment]
@carocad sure. I'll work on it this evening.

**Comment by mehdisadeghi** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@carocad/hive?release-channel=expo-ci

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by mehdisadeghi** [comment]
@carocad Wow! It's working!

**Comment by carocad** [comment]
@mehdisadeghi sorry it was my fault that `appr` was not working. I had switched in travis to build on every push instead of on pull request.

However, there is no space for comments if you just push to a branch. It has to be on pull request :D

Now it works !!! 🚀

**Comment by mehdisadeghi** [comment]
Apparently there is a env problem. When I scan the above app I get an error which complains that MAPBOX and AUTH0 env vars are missing. Shall we set them in travis?

**Comment by carocad** [comment]
@mehdisadeghi I just did :)

**Comment by mehdisadeghi** [comment]
I triggered a new build, we'll see in a few minutes :)

**Comment by mehdisadeghi** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@carocad/hive?release-channel=expo-ci

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by mehdisadeghi** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@carocad/hive?release-channel=expo-ci

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by mehdisadeghi** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@carocad/hive?release-channel=expo-ci

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by mehdisadeghi** [comment]
@carocad congrats! :)

**Comment by carocad** [comment]
@mehdisadeghi to you too :)

**Pull request merged**
