### PR TITLE
Fix displaced search box. Close #83

### LINKED ISSUE #83: Searchbox is slightly displaced on Samsung Galaxy S8

### PR DESCRIPTION
**Pull request by mehdisadeghi**

### CODE REVIEW

**Comment by carocad** [comment]
@mehdisadeghi I did a small change to avoid extra components. Please double check that it has the intended effect on your phone ;)

**Comment by mehdisadeghi** [comment]
It would be nice if we could try hive build using expo for each PR on the go. Because now i have to go home and try it there

**Comment by carocad** [comment]
@mehdisadeghi I think this could be possible with expo releases. I havent done one in a while though. I guess it would make for a better workflow.

If you want to check that out it would be great. AFAIK it is something like `exp release`. The app is then stored in expo servers and then you would have to scan the QR code on the website.

**Comment by mehdisadeghi** [comment]
It's a nice to have, however setting it up for each PR doesn't sound easy.

**Pull request merged**
